ProductManagement.WebUI/Areas/ManagementPanel/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Entities.Models;
using ProductManagement.WebUI.Helpers;

namespace ProductManagement.WebUI.Areas.ManagementPanel.Controllers {
    [Authorize]

    [Area("ManagementPanel")]
    public class ContactsController : Controller {
        private readonly IWebHostEnvironment _environment;
        private readonly ProductManagementContext _context = new
ProductManagementContext();
        public ContactsController(IWebHostEnvironment environment) {
            _environment = environment;
        }

        // GET: ManagementPanel/Contacts
        public async Task<IActionResult> Index() {
           return View(await _context.Contacts.FirstOrDefaultAsync());
        }

        
        // GET: ManagementPanel/Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null || _context.Contacts == null) {
                return NotFound();
            }

            var contact = await _context.Contacts.FindAsync(id);
            if (contact == null) {
                return NotFound();
            }
            return View(contact);
        }

        // POST: ManagementPanel/Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( Contact contact, IFormFile? img) { 
            if (ModelState.IsValid) {
                try {
                    var editContact = await _context.Contacts.FindAsync(contact.Id); 
                    if (img != null) {
                        editContact.ImageURL = await UploadHelper.UploadImageAsync(_environment, img);
                    }
                    editContact.Title = contact.Title;
                    editContact.Description = contact.Description;
                    editContact.Phone = contact.Phone;
                    editContact.Email = contact.Email;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!ContactExists(contact.Id)) {
                        return NotFound();
                    }
                    else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }
         
        private bool ContactExists(int id) {
            return (_context.Contacts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProductManagement.WebUI/Areas/ManagementPanel/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Entities.Models;

namespace ProductManagement.WebUI.Areas.ManagementPanel.Controllers {
    [Authorize]
    [Area("ManagementPanel")]
    public class MessagesController : Controller { 
        private readonly ProductManagementContext _context = new
ProductManagementContext();
        

        // GET: ManagementPanel/Messages
        public async Task<IActionResult> Index() {
            return View(await _context.Messages.ToListAsync());
        }

        // GET: ManagementPanel/Messages/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null || _context.Messages == null) {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null) {
                return NotFound();
            }

            return View(message);
        }
   
    }
}

ProductManagement.WebUI/Areas/ManagementPanel/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Entities.Models;
using ProductManagement.WebUI.Helpers;

namespace ProductManagement.WebUI.Areas.ManagementPanel.Controllers {
    [Authorize]
    [Area("ManagementPanel")]
    public class ProductsController : Controller {
        private readonly ProductManagementContext _context = new ProductManagementContext();

        private readonly IWebHostEnvironment _environment;  

        public ProductsController(IWebHostEnvironment environment) {
            _environment = environment;
        }

        // GET: ManagementPanel/Products
        public async Task<IActionResult> Index() {
            var products = await _context.Products.Include("ProductDetail").ToListAsync();
            return View(products);
        }

        // GET: ManagementPanel/Products/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null || _context.Products == null) {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null) {
                return NotFound();
            }

            return View(product);
        }

        // GET: ManagementPanel/Products/Create
        public IActionResult Create() {
            return View();
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile? img) {
            if (ModelState.IsValid) {
                if (img!= null) {
                    product.ImageURL = await UploadHelper.UploadImageAsync(_environment, img);
                }
                product.Status = true;
                product.CreatedDate = DateTime.Now;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: ManagementPanel/Products/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null || _context.Products == null) {
                return NotFound();
            }

            var product = await _context.Products.Include(t => t.ProductDetail).FirstOrDefaultAsync(r => r.Id == id);
            if (product == null) {
                return NotFound();
            }
            return View(product);
        }

        // POST: ManagementPanel/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product, IFormFile? img) { 
            if (ModelState.IsValid) {
                try {
                    var editProduct = await _context.Products.Include(x => x.ProductDetail).FirstOrDefaultAsync(t => t.Id == product.Id);
                    if (img != null) {
                        editProduct.ImageURL = await UploadHelper.UploadImageAsync(_environment, img);
                    }

                    editProduct.Status = product.Status;
                    editProduct.Name = product.Name;
                    editProduct.Price = product.Price;
                    editProduct.ProductDetail.Description = product.ProductDetail.Description;
                    editProduct.ProductDetail.IsBestSeller = product.ProductDetail.IsBestSeller; 
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

    }
}

ProductManagement.WebUI/Areas/ManagementPanel/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Entities.Models;

namespace ProductManagement.WebUI.Areas.ManagementPanel.Controllers {
    [Authorize]
    [Area("ManagementPanel")]
    public class UsersController : Controller {
        private readonly ProductManagementContext _context = new ProductManagementContext();

        // GET: ManagementPanel/Users
        public async Task<IActionResult> Index() {
            return View(await _context.Users.Where(x => x.Status == true).ToListAsync());
        }
         

        // GET: ManagementPanel/Users/Create
        public IActionResult Create() {
            return View();
        }

        // POST: ManagementPanel/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( User user) {
            if (ModelState.IsValid) {
                user.Status = true;
                user.CreatedDate = DateTime.Now;
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: ManagementPanel/Users/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null || _context.Users == null) {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null) {
                return NotFound();
            }
            return View(user);
        }

        // POST: ManagementPanel/Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(User user) { 
            if (ModelState.IsValid) {
                try {
                    var editUser = await _context.Users.FindAsync(user.Id);
                    editUser.Status = user.Status;
                    editUser.Email = user.Email;
                    editUser.LastName = user.LastName;
                    editUser.FirstName = user.FirstName;
                    editUser.Password = user.Password;
                    editUser.Phone = user.Phone;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: ManagementPanel/Users/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null || _context.Users == null) {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null) {
                return NotFound();
            }

            return View(user);
        }

        // POST: ManagementPanel/Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (_context.Users == null) {
                return Problem("Entity set 'ProductManagementContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            user.Status = false; 

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
         
    }
}

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Footer.cshtml
	<!--footer -->
<div class="footer">
	<p class="mb-0">
		Syndash 2020 | Developed By : <a href="https://themeforest.net/user/codervent" target="_blank">codervent</a>
	</p>
</div>
<!-- end footer -->

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Head.cshtml
	<!-- Required meta tags -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title>Syndash </title>
<!--favicon-->
<link rel="icon" href="~/areas/images/favicon-32x32.png" type="image/png" />
<!-- Vector CSS -->
<link href="~/areas/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
<!--plugins-->
<link href="~/areas/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
<link href="~/areas/plugins/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" />
<link href="~/areas/plugins/metismenu/css/metisMenu.min.css" rel="stylesheet" />
<!-- loader-->
<link href="~/areas/css/pace.min.css" rel="stylesheet" />
<script src="~/areas/js/pace.min.js"></script>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="~/areas/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&amp;family=Roboto&amp;display=swap" />
<!-- Icons CSS -->
<link rel="stylesheet" href="~/areas/css/icons.css" />
<!-- App CSS -->
<link rel="stylesheet" href="~/areas/css/app.css" />
<link rel="stylesheet" href="~/areas/css/dark-sidebar.css" />
<link rel="stylesheet" href="~/areas/css/dark-theme.css" />

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Header.cshtml
 @using System.Security.Claims;
   <!--header-->
<header class="top-header">
    <nav class="navbar navbar-expand">
        <div class="left-topbar d-flex align-items-center">
            <a href="javascript:;" class="toggle-btn">
                <i class="bx bx-menu"></i>
            </a>
        </div>
        <div class="flex-grow-1 search-bar">
            <div class="input-group">
                <div class="input-group-prepend search-arrow-back">
                    <button class="btn btn-search-back" type="button">
                        <i class="bx bx-arrow-back"></i>
                    </button>
                </div>
                <input type="text" class="form-control" placeholder="search" />
                <div class="input-group-append">
                    <button class="btn btn-search" type="button">
                        <i class="lni lni-search-alt"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="right-topbar ml-auto">
            <ul class="navbar-nav">
                <li class="nav-item search-btn-mobile">
                    <a class="nav-link position-relative" href="javascript:;">
                        <i class="bx bx-search vertical-align-middle"></i>
                    </a>
                </li>
                <li class="nav-item dropdown dropdown-user-profile">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="javascript:;" data-toggle="dropdown">
                        <div class="media user-box align-items-center">
                            <div class="media-body user-info">

                                @if (User.FindFirst(ClaimTypes.Name) != null) {
                                    <span>@User.FindFirst(ClaimTypes.Name).Value</span>
                                }
                                <p class="designattion mb-0">Available</p>
                            </div>
                            <img src="~/areas/images/avatars/avatar-1.png" class="user-img" alt="user avatar">
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        
                        <div class="dropdown-divider mb-0"></div>	<a class="dropdown-item" href="@Url.Action("Logout", "Account")">
                            <i class="bx bx-power-off"></i><span>Çıkış yap</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--end header-->

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    @Html.Partial("_Head")
</head>

<body>
    <!-- wrapper -->
    <div class="wrapper">
        @Html.Partial("_Sidebar")
        @Html.Partial("_Header")
        <!--page-wrapper-->
        <div class="page-wrapper">
            <!--page-content-wrapper-->
            <div class="page-content-wrapper">
                <div class="page-content">
                    @RenderBody()
                </div>
            </div>
            <!--end page-content-wrapper-->
        </div>
        <!--end page-wrapper-->
        <!--start overlay-->
        <div class="overlay toggle-btn-mobile"></div>
        <!--end overlay-->
        <!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
        <!--End Back To Top Button-->
        @Html.Partial("_Footer")
    </div>
    <!-- end wrapper -->
    <!-- JavaScript -->
    @Html.Partial("_Scripts")
</body>

</html>

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Scripts.cshtml
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="~/areas/js/jquery.min.js"></script>
<script src="~/areas/js/popper.min.js"></script>
<script src="~/areas/js/bootstrap.min.js"></script>
<!--plugins-->
<script src="~/areas/plugins/simplebar/js/simplebar.min.js"></script>
<script src="~/areas/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="~/areas/plugins/perfect-scrollbar/js/perfect-scrollbar.js"></script>
<!-- Vector map JavaScript -->
<script src="~/areas/plugins/vectormap/jquery-jvectormap-2.0.2.min.js"></script>
<script src="~/areas/plugins/vectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="~/areas/plugins/vectormap/jquery-jvectormap-in-mill.js"></script>
<script src="~/areas/plugins/vectormap/jquery-jvectormap-us-aea-en.js"></script>
<script src="~/areas/plugins/vectormap/jquery-jvectormap-uk-mill-en.js"></script>
<script src="~/areas/plugins/vectormap/jquery-jvectormap-au-mill.js"></script>
<script src="~/areas/plugins/apexcharts-bundle/js/apexcharts.min.js"></script>
<script src="~/areas/js/index.js"></script>
<!-- App JS -->
<script src="~/areas/js/app.js"></script>
<script>
	new PerfectScrollbar('.dashboard-social-list');
	new PerfectScrollbar('.dashboard-top-countries');
</script>

ProductManagement.WebUI/Areas/ManagementPanel/Views/Shared/_Sidebar.cshtml
    <!--sidebar-wrapper-->
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div class="">
            <img src="~/areas/images/logo-icon.png" class="logo-icon-2" alt="" />
        </div>
        <div>
            <h4 class="logo-text">Syndash</h4>
        </div>
        <a href="javascript:;" class="toggle-btn ml-auto">
            <i class="bx bx-menu"></i>
        </a>
    </div>
    <!--navigation-->
    <ul class="metismenu" id="menu">
        <li>
            <a href="@Url.Action("Index","Dashboard")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Giriş</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","MainPages")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Anasayfa</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Contacts")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">İletişim</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Abouts")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Hakkımızda</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Users")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Kullanıcılar</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Products")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Ürünler</div>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Messages")">
                <div class="parent-icon icon-color-2">
                    <i class="bx bx-envelope"></i>
                </div>
                <div class="menu-title">Mesajlar</div>
            </a>
        </li>
    </ul>
    <!--end navigation-->
</div>
<!--end sidebar-wrapper-->