ProductManagement.WebUI/Areas/ManagementPanel/Controllers/MainPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Entities.Models;
using ProductManagement.WebUI.Helpers;

namespace ProductManagement.WebUI.Areas.ManagementPanel.Controllers {
    [Authorize]
    [Area("ManagementPanel")]
    public class MainPagesController : Controller {
        private readonly IWebHostEnvironment _environment;
        private readonly ProductManagementContext _context = new 
ProductManagementContext();
        public MainPagesController(IWebHostEnvironment environment) {
            _environment = environment;
        }
        // GET: ManagementPanel/MainPages
        public async Task<IActionResult> Index() {
            var mainPage =  await _context.MainPages.FirstOrDefaultAsync();
            return View(mainPage);
        }
          
        // GET: ManagementPanel/MainPages/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null || _context.MainPages == null) {
                return NotFound();
            }

            var mainPage = await _context.MainPages.FindAsync(id);
            if (mainPage == null) {
                return NotFound();
            }
            return View(mainPage);
        }

        // POST: ManagementPanel/MainPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MainPage mainPage, IFormFile? img) { 
            if (ModelState.IsValid) {
                try {
                    var editMainPage = await _context.MainPages.FindAsync(mainPage.Id);
                    if (img != null) {
                        editMainPage.ImageURL = await UploadHelper.UploadImageAsync(_environment, img);
                    }
                    editMainPage.Title = mainPage.Title;
                    editMainPage.Description = mainPage.Description;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {  
                        throw; 
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mainPage);
        }
        
    }
}

ProductManagement.WebUI/Areas/ManagementPanel/Views/MainPages/Edit.cshtml
@model ProductManagement.Entities.Models.MainPage

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Anasayfa Düzenle</h1>

@using (Html.BeginForm("Edit", "MainPages", FormMethod.Post,
new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class="text-danger"})
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes:
        new {@class="control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" accept="image/*" name="img" id="img" />
            </div>
        </div>
         
        <div class="form-group">
            <label class="control-label col-md-2">Başlık</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title,new { htmlAttributes= new {@class="form-control"} })
                @Html.ValidationMessageFor(model => model.Title, "", new {@class="text-danger"})
            </div>
        </div>
          
        <div class="form-group">
            <label class="control-label col-md-2">Açıklama</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description,new { htmlAttributes= new {@class="form-control"} })
                @Html.ValidationMessageFor(model => model.Description, "", new {@class="text-danger"})
            </div>
        </div>
          

        <br />
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
} 

ProductManagement.WebUI/Areas/ManagementPanel/Views/MainPages/Index.cshtml
@model ProductManagement.Entities.Models.MainPage

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Anasayfa Bilgileri</h1>

<a class="btn btn-danger" href="@Url.Action("Edit", "MainPages", new {id=Model.Id})">Düzenle</a>
 
<div class=""> 
    <img src="@Model.ImageURL" />
    <hr />
    <h2>@Model.Title</h2>
    <p>@Model.Description</p>
</div> 